openapi: 3.0.0
info:
  description: RecipeAPI
  version: '1.0.0'
  title: 'Recipe API'
  contact:
    email: space12.3d@gmail.com
    name: Recipe support Team

tags:
  - name: Recipe
    description: All the operations related to recipes

paths:
 "/v1/recipes":
    get:
      tags:
        - Recipe
      summary: Gets all available recipes
      description: |
        Gets all available recipes
      operationId: getAvailableRecipes
      responses:
        '200':
          description: Returns available recipe
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeObject'
    post:
      tags:
        - Recipe
      requestBody:
        $ref: "#/components/requestBodies/CreateRecipe"
      summary: Creates a recipes
      operationId: createRecipe
      description: |
        Creates a Recipe
      responses:
        "201":
          $ref: "#/components/responses/CreateRecipeResponse"
        "422":
          description: Incorrect Recipe detail provided
          content:
            application/json:
              schema:
                $ref: "shared-components.yaml#/components/schemas/ErrorObject"
        "409":
          description: Recipe already exists
          content:
            application/json:
              schema:
                $ref: "shared-components.yaml#/components/schemas/ErrorObject"
 "/v1/recipes/categories":
    get:
      tags:
        - Recipe
      summary: Gets all available categories
      description: |
        Gets all available categories
      operationId: getAvailableCategories
      responses:
        '200':
          description: Returns available categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryObject'
 "/v1/recipes/categories/{id}":
    get:
      tags:
        - Recipe
      summary: Gets a Recipe given its Category id
      operationId: getRecipe
      description: |
        Gets a Recipe by Category id
      parameters:
        - $ref: "shared-components.yaml#/components/parameters/IdPathParam"
      responses:
        "200":
          description: Returns the specific Recipe matching the passed id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeObject"
        "404":
          description: Recipe not found
          content:
            application/json:
              schema:
                $ref: "shared-components.yaml#/components/schemas/ErrorObject"
 "/v1/recipes/search":
    get:
      tags:
        - Recipe
      summary: Gets a Recipe given its recipe name and category name
      operationId: getRecipeByName
      description: |
        Gets a Recipe by Recipe and category name
      parameters:
                  - in: query
                    name: recipeName
                    required: true
                    schema:
                        type: string
                        description: recipe title
                        example: 'Another zuccini'
                  - in: query
                    name: categoryName
                    schema:
                        type: string
                        example: "Main dish"
                        description: categoy name
      responses:
        "200":
          description: Returns the specific Recipe matching names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeObject"
        "404":
          description: Recipe not found
          content:
            application/json:
              schema:
                $ref: "shared-components.yaml#/components/schemas/ErrorObject"

components:
  schemas:
    RecipeObject:
      type: object
      properties:
        recipeId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426655440000"
        creationTimestamp:
          type: string
          format: 'date-time'
        head:
           type: object
           properties:
            title:
              type: string
              example: "title"
            yield:
              type: integer
              example: 6
            categories:
              type: array
              items:
                $ref: '#/components/schemas/CategoryObject' 
        ingredients:
              type: array
              items:
                $ref: '#/components/schemas/IngredientObject'
        directions:
              type: object
              properties:
               step:
                 type: string
                 example: "steps..."

    CategoryObject:
      type: object
      properties:
        categoryId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426655440000"
        categoryName:
            type: string
            example: "Main dish"
    
    IngredientObject:
        type: object
        properties:
          title:
            type: string
            example: "title"
          Items:
            type: array
            $ref: '#/components/schemas/IngredientItemsObject'

    IngredientItemsObject:
      type: object
      properties:
        amount:
           type: object
           properties:
            quantity:
              type: integer
              example: 6
            unit:
              type: string
              example: "pound"
        item:
            type: string
            example: "Onion; large, chopped"
    CreateRecipeResponseObject:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
  requestBodies:
    #Recipes
    CreateRecipe:
      description: The Recipe creation details
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RecipeObject"
  responses:
    CreateRecipeResponse:
      description: The create recipe response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateRecipeResponseObject"